In [1]:
import pandas as pd

In [9]:
df = pd.read_csv('../data/AI_SocialMedia_Student_Health_Dataset_clean.csv')

In [10]:
df.shape

(15000, 14)

In [11]:
df.columns

Index(['Student_ID', 'Age', 'Gender', 'Education_Level',
       'Daily_Social_Media_Hours', 'Daily_AI_Tool_Usage_Hours', 'Sleep_Hours',
       'Physical_Activity_Hours', 'Mental_Health_Score',
       'Physical_Health_Score', 'Social_Isolation_Score', 'Burnout_Level',
       'Academic_Performance_Score', 'Academic_Failure_Risk'],
      dtype='str')

In [12]:
df.dtypes

Student_ID                        str
Age                             int64
Gender                            str
Education_Level                   str
Daily_Social_Media_Hours      float64
Daily_AI_Tool_Usage_Hours     float64
Sleep_Hours                   float64
Physical_Activity_Hours       float64
Mental_Health_Score           float64
Physical_Health_Score         float64
Social_Isolation_Score        float64
Burnout_Level                     str
Academic_Performance_Score    float64
Academic_Failure_Risk           int64
dtype: object

In [14]:
df.head()

,Student_ID,Age,Gender,Education_Level,Daily_Social_Media_Hours,Daily_AI_Tool_Usage_Hours,Sleep_Hours,Physical_Activity_Hours,Mental_Health_Score,Physical_Health_Score,Social_Isolation_Score,Burnout_Level,Academic_Performance_Score,Academic_Failure_Risk
0,STU_00001,19,Male,College,5.32,1.21,7.30,1.41,74.06,98.90,4.05,Low,88.80,0
1,STU_00002,16,Non-binary,High School,5.21,3.89,7.81,2.48,76.13,89.94,4.65,Moderate,50.60,0
2,STU_00003,25,Male,University,3.61,2.65,6.34,0.06,65.01,76.75,5.28,Low,96.67,0
3,STU_00004,23,Male,University,2.93,1.43,6.12,1.37,74.67,87.38,3.66,Low,85.65,0
4,STU_00005,20,Non-binary,College,6.52,1.64,5.23,1.14,67.74,88.04,3.25,Moderate,71.84,0

In [16]:
df.isnull().sum()

Student_ID                    0
Age                           0
Gender                        0
Education_Level               0
Daily_Social_Media_Hours      0
Daily_AI_Tool_Usage_Hours     0
Sleep_Hours                   0
Physical_Activity_Hours       0
Mental_Health_Score           0
Physical_Health_Score         0
Social_Isolation_Score        0
Burnout_Level                 0
Academic_Performance_Score    0
Academic_Failure_Risk         0
dtype: int64

In [20]:
df.describe(include='all')

,Student_ID,Age,Gender,Education_Level,Daily_Social_Media_Hours,Daily_AI_Tool_Usage_Hours,Sleep_Hours,Physical_Activity_Hours,Mental_Health_Score,Physical_Health_Score,Social_Isolation_Score,Burnout_Level,Academic_Performance_Score,Academic_Failure_Risk
count,15000,15000.000000,15000,15000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000,15000.000000,15000.000000
unique,15000,NaN,3,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,NaN,NaN
top,STU_00001,NaN,Male,High School,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Low,NaN,NaN
freq,1,NaN,7265,5693,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9000,NaN,NaN
mean,NaN,19.040667,NaN,NaN,4.537500,2.584580,6.544205,1.246332,72.513156,88.019761,4.312027,NaN,78.314859,0.060000
std,NaN,3.767257,NaN,NaN,2.398494,1.677988,1.269770,1.038349,9.245482,9.684253,1.162432,NaN,11.544651,0.237495
min,NaN,13.000000,NaN,NaN,0.000000,0.000000,2.000000,0.000000,32.560000,48.030000,0.970000,NaN,23.990000,0.000000
25%,NaN,16.000000,NaN,NaN,2.830000,1.310000,5.680000,0.310000,66.780000,81.520000,3.470000,NaN,70.530000,0.000000
50%,NaN,19.000000,NaN,NaN,4.500000,2.510000,6.550000,1.130000,73.760000,89.470000,4.280000,NaN,78.590000,0.000000
75%,NaN,22.000000,NaN,NaN,6.180000,3.740000,7.410000,1.950000,79.580000,97.160000,5.120000,NaN,86.700000,0.000000
max,NaN,25.000000,NaN,NaN,14.000000,9.500000,11.150000,5.000000,91.760000,99.980000,8.410000,NaN,99.980000,1.000000

In [17]:
df.duplicated().sum()

np.int64(0)

In [26]:
categorical_cols = ['Gender', 'Education_Level', 'Academic_Failure_Risk']

for col in categorical_cols:
    print(col, ':', df[col].unique())

Gender : <StringArray>
['Male', 'Non-binary', 'Female']
Length: 3, dtype: str
Education_Level : <StringArray>
['College', 'High School', 'University']
Length: 3, dtype: str
Academic_Failure_Risk : [0 1]